// styles/homeStyles.ts
import { StyleSheet } from "react-native";

export const getStyles = (c: any) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: c.background },
    center: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: c.background },
    headerPerfil: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 20, paddingTop: 10, paddingBottom: 15 },
    fotoPerfilMin: { width: 44, height: 44, borderRadius: 22, marginRight: 12, backgroundColor: c.border },
    boasVindas: { fontSize: 18, fontWeight: "bold", color: c.text },
    pillFamilia: { flexDirection: "row", alignItems: "center", backgroundColor: c.border, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, marginTop: 4 },
    textoPillFamilia: { fontSize: 11, color: c.tint, fontWeight: "bold" },
    inputAuth: { backgroundColor: c.border, paddingHorizontal: 16, paddingVertical: 18, borderRadius: 16, fontSize: 16, color: c.text, fontWeight: "500" },
    permissaoCard: { backgroundColor: c.card, padding: 30, borderRadius: 24, alignItems: "center", width: "85%", elevation: 10 },
    permissaoTitulo: { fontSize: 20, fontWeight: "bold", color: c.text, marginTop: 15, marginBottom: 8 },
    textoPermissao: { fontSize: 15, color: c.textSecondary, textAlign: "center", marginBottom: 25, lineHeight: 22 },
    walletCard: { backgroundColor: c.card, margin: 16, padding: 20, borderRadius: 24, elevation: 3, shadowColor: "#000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 8 },
    walletHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
    walletTitle: { fontSize: 16, fontWeight: "bold", color: c.text, marginLeft: 8 },
    pontoNuvem: { position: "absolute", top: -2, right: -4, width: 8, height: 8, borderRadius: 4, backgroundColor: c.warning },
    btnRecarga: { flexDirection: "row", backgroundColor: c.tint, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, alignItems: "center" },
    textoBtnRecarga: { color: "white", fontWeight: "bold", fontSize: 12, marginLeft: 4 },
    btnRemover: { flexDirection: "row", backgroundColor: "transparent", paddingHorizontal: 6, paddingVertical: 6, borderRadius: 8, alignItems: "center" },
    labelSaldo: { fontSize: 12, color: c.textSecondary, fontWeight: "bold", textTransform: "uppercase" },
    valorSaldo: { fontSize: 44, fontWeight: "900", letterSpacing: -1.5, marginBottom: 10 },
    infoRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 12 },
    infoText: { fontSize: 12, color: c.textSecondary, fontWeight: "600" },
    barraFundo: { height: 8, backgroundColor: c.border, borderRadius: 4, overflow: "hidden" },
    barraProgresso: { height: "100%", borderRadius: 4 },
    textoPorcentagem: { fontSize: 12, color: c.textSecondary, marginTop: 8, textAlign: "right", fontWeight: "500" },
    botoesAcaoContainer: { flexDirection: "row", paddingHorizontal: 16, marginBottom: 10 },
    btnAcaoScan: { flex: 1, backgroundColor: c.warning, paddingVertical: 14, borderRadius: 16, flexDirection: "row", justifyContent: "center", alignItems: "center", marginRight: 12, elevation: 2 },
    btnAcaoManual: { flex: 1, backgroundColor: c.card, paddingVertical: 14, borderRadius: 16, flexDirection: "row", justifyContent: "center", alignItems: "center", borderWidth: 1, borderColor: c.info },
    textoBotaoAcaoBranco: { color: "white", fontWeight: "bold", fontSize: 15, marginLeft: 8 },
    textoBotaoAcaoAzul: { color: c.info, fontWeight: "bold", fontSize: 15, marginLeft: 8 },
    scannerContainer: { height: 180, marginHorizontal: 16, marginBottom: 10, borderRadius: 20, overflow: "hidden", backgroundColor: "#000" },
    overlayScanner: { backgroundColor: "rgba(0,0,0,0.3)", justifyContent: "center", alignItems: "center" },
    miraScanner: { alignItems: "center", justifyContent: "center" },
    btnModoRapido: { position: "absolute", bottom: 20, alignSelf: "center", alignItems: "center", padding: 10 },
    btnModoRapidoAtivo: { backgroundColor: "rgba(0,0,0,0.5)", borderRadius: 16 },
    btnLanterna: { position: "absolute", top: 12, left: 12, zIndex: 10, padding: 4 },
    btnFecharScanner: { position: "absolute", top: 12, right: 12, zIndex: 10 },
    listaContainer: { flex: 1, paddingHorizontal: 16 },
    headerLista: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12, marginTop: 8 },
    tituloSecao: { fontSize: 16, fontWeight: "bold", color: c.text },
    btnLimparTexto: { color: c.warning, fontWeight: "bold", fontSize: 13 },
    emptyState: { alignItems: "center", marginTop: 40 },
    listaVazia: { color: c.textSecondary, fontSize: 15, marginTop: 12, fontWeight: "500" },
    itemCarrinho: { flexDirection: "row", backgroundColor: c.card, padding: 16, borderRadius: 20, marginBottom: 10, alignItems: "center", justifyContent: "space-between", elevation: 1 },
    itemCarrinhoAlerta: { borderWidth: 1, borderColor: "#FFC857", backgroundColor: "#FFFAED" },
    itemInfo: { flexDirection: "row", alignItems: "center", flex: 1 },
    miniature: { width: 44, height: 44, borderRadius: 12, marginRight: 12 },
    miniaturePlaceholder: { width: 44, height: 44, borderRadius: 12, marginRight: 12, backgroundColor: c.border, justifyContent: "center", alignItems: "center" },
    itemNome: { fontSize: 15, fontWeight: "700", color: c.text, marginBottom: 2 },
    itemPrecoUnid: { fontSize: 12, color: c.textSecondary, fontWeight: "500" },
    itemSubtotal: { fontSize: 16, fontWeight: "800", color: "#FFC857" },
    footerFloat: { position: "absolute", bottom: 0, left: 0, right: 0, padding: 16, backgroundColor: c.overlay },
    btnFinalizar: { backgroundColor: c.tint, paddingVertical: 16, borderRadius: 16, flexDirection: "row", alignItems: "center", justifyContent: "center", elevation: 3 },
    modalBackdropCentral: { flex: 1, backgroundColor: "rgba(0,0,0,0.7)", justifyContent: "center", padding: 20 },
    modalContentCentral: { backgroundColor: c.card, borderRadius: 24, padding: 24, alignItems: "center" },
    modalBackdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,0.8)" },
    modalContent: { backgroundColor: c.card, borderTopLeftRadius: 32, borderTopRightRadius: 32, paddingBottom: 20, maxHeight: "90%" },
    dragPill: { width: 40, height: 5, backgroundColor: c.borderDark, borderRadius: 3, alignSelf: "center", marginTop: 12 },
    modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 24, paddingTop: 16, paddingBottom: 10 },
    modalTitulo: { fontSize: 20, fontWeight: "bold", color: c.text },
    btnClose: { padding: 4, backgroundColor: c.border, borderRadius: 20 },
    modalForm: { paddingHorizontal: 24 },
    alertaInflacao: { backgroundColor: "#FFC857", padding: 12, borderRadius: 12, flexDirection: "row", alignItems: "center", marginBottom: 15 },
    textoInflacao: { color: "#1E1E1E", fontSize: 13 },
    inputGroup: { marginBottom: 12 },
    labelField: { fontSize: 11, color: c.textSecondary, marginBottom: 6, fontWeight: "bold", letterSpacing: 0.5 },
    inputModal: { backgroundColor: c.border, paddingHorizontal: 16, paddingVertical: 14, borderRadius: 12, fontSize: 16, color: c.text, fontWeight: "500" },
    inputGigante: { backgroundColor: c.border, width: "100%", padding: 16, borderRadius: 12, fontSize: 24, fontWeight: "bold", textAlign: "center", marginBottom: 20 },
    rowInputs: { flexDirection: "row" },
    catPill: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: c.border, marginRight: 10, borderWidth: 1, borderColor: "transparent" },
    catPillActive: { backgroundColor: c.border, borderColor: c.tint, borderWidth: 1 },
    catText: { color: c.textSecondary, fontWeight: "600", fontSize: 13 },
    catTextActive: { color: c.tint },
    rowFotos: { flexDirection: "row", justifyContent: "space-between", marginBottom: 24 },
    boxFotoContainer: { width: "48%", position: "relative" },
    boxFoto: { height: 90, backgroundColor: c.border, borderRadius: 16, borderWidth: 1, borderColor: c.info, borderStyle: "dashed", justifyContent: "center", alignItems: "center", overflow: "hidden" },
    btnRemoverFoto: { position: "absolute", top: -8, right: -8, backgroundColor: c.danger, width: 26, height: 26, borderRadius: 13, justifyContent: "center", alignItems: "center", elevation: 2, zIndex: 10 },
    textBtnFoto: { color: c.info, fontSize: 13, fontWeight: "700", marginTop: 6 },
    imagePreview: { width: "100%", height: "100%" },
    btnAdicionarCarrinho: { backgroundColor: c.info, paddingVertical: 16, borderRadius: 16, alignItems: "center", marginBottom: 20 },
    btnConfirmarDep: { width: "100%", padding: 16, borderRadius: 12, alignItems: "center", marginBottom: 16 },
    btnPrimary: { backgroundColor: c.warning, paddingVertical: 14, paddingHorizontal: 30, borderRadius: 16 },
    btnCalcFlutuante: { position: "absolute", bottom: 90, right: 20, padding: 16, borderRadius: 30, elevation: 5, shadowColor: "#000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 4, flexDirection: "row", alignItems: "center", zIndex: 10 },
    overlayPreviaFoto: { justifyContent: "space-between" },
    headerPrevia: { flexDirection: "row", padding: 20, alignItems: "center", justifyContent: "space-between", backgroundColor: "rgba(0,0,0,0.6)" },
    textoHeaderPrevia: { color: "white", fontWeight: "bold", fontSize: 16 },
    footerPrevia: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 30, paddingBottom: 50, backgroundColor: "rgba(0,0,0,0.6)" },
    btnCancelarFoto: { width: 80, alignItems: "center" },
    btnShutter: { width: 76, height: 76, borderRadius: 38, backgroundColor: "white", justifyContent: "center", alignItems: "center", borderWidth: 4, borderColor: "rgba(255,255,255,0.3)" },
    shutterInternal: { width: 60, height: 60, borderRadius: 30, backgroundColor: "white", borderWidth: 2, borderColor: "#1E1E1E" },
  });